### ISSUE TITLE
Configurar DataTables-JS conforme Português do Brasil

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/site#10]
Na API teste, http://addressforall.org/api-test2 falta

- [x] dar opção de paginação maior ou sem paginação (se dentro de limites aceitáveis de tamanho)
- [x] garantir que a ordenação respeite a nossa língua.

O respeito ao Português do Brasil é conseguido com "locale", https://datatables.net/blog/2017-02-28
e nos filtros talvez opcional desacentuador,  https://datatables.net/plug-ins/filtering/type-based/accent-neutralise
que mantém válida a busca acentuada.

**Comment by venezianluis** [comment]
commit 9578649403c7f25cc99b767789d7851a1a06c4ad

**Comment by ppKrauss** [comment]
resolvido
