### ISSUE TITLE
Atualizar APIs para teste depois para definitivo

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/site#17]
Conforme [Novidades](https://github.com/AddressForAll/WS/wiki/Novidades), temos por fim a infraestrutura definitiva... Hora de revisar o codigo das implementacoes de teste e refatorar... Por seguranca melhor implementar modificacoes e testar por partes.

## Consolidar por partes
* Implementando tudo em API-TEST (so depois API definitiva).

    - [x] atualizar [api-donor.js](https://github.com/AddressForAll/site/blob/master/resources/js/api-donor.js) com `http://api-test.addressforall.org/vw_core/donor/{param}` onde param pode ser shortname, id, vat_id ou wikidata_id.
    - [x] atualizar [api-eclusa.js](https://github.com/AddressForAll/site/blob/master/resources/js/api-eclusa.js) com `http://api-test.addressforall.org/v1/eclusa/checkuserfiles_step{step}/{user}/{user_type}`.
    - [x] atualizar [api-origin.js](https://github.com/AddressForAll/site/blob/master/resources/js/api-origin.js) com `http://api-test.addressforall.org/_sql/origin` ou algo mais especifico (solicitar!) baseado em `vw_core/origin`.

## APIS HTML definitivas
Todas serao **publicadas no *endpoint* `/v1.htm/`**, redirecionadas pelo NGINX para paginas PHP.  Falta preparar o PHP definitivo.

Colocar novas APIs no ar nao eh problema &mdash; basta declarar a nova funcao como feito em [WS/src/step01-iniApi.sql](https://github.com/AddressForAll/WS/blob/master/src/step01-iniApi.sql) (ver funcoes `API.uridisp_vw_core`) ou [Eclusa](https://github.com/AddressForAll/digital-preservation/blob/master/src/eclusa-step1-ini.sql) (ver funcoes `API.uridisp_eclusa`)... As versoes JSON e CSV sao automaticamente criadas.

O problema eh a cada novo endpoint criado:
1. Decidir se realmente precisa de versao HTML (ai na pagina apenas constarao links e aviso "esta funcao nao foi implementada em *demo HTML*).
2. Avaliar quais Javascript reusar
3. Implementar.

## APIs estaveis definitivas
Aguardamos estabilizacao da base DL03 atual para que ela se torne DL04.

* Para adaptar os codigos acima basta **trocar o subdominio `api-test` por `api`** que a base sera trocada de DL03 para DL04.
* Falta revisar os dados OSM (ruas e enderecos), IBGE (faces de quadra) e Correios (nomes de rua e relacao CEP-quadra). Prefeituras por hora apenas tres.
* Com a definicao da navegacao oficial no site, com mapas e graficos, teremos um referencial para fechar as APIs definitivas.

## Novos endpoints
Validos para API e API-TEST,

* `/v1/vw_core/jurisdiction/{isolabel_ext|osm_id|urn_lex|iso_abrevs}` ou `/v1/vw_core/jurisdiction/{jurisdBase_num|jurisdBase_abrev}/{jurisdLocal_num}` ... Ver exemplos no link novidades. Usaremos iframe OSM e/ou thumb map Wikidata.
* ... revisando demais
* ...

**Comment by venezianluis** [comment]
### Pendente de migração: 
- **Donor:** URL precisa retornar todos os registros quando houver ausência de parâmetro.
- **Origin:** 
    - *Atributos:* Há no antigo banco `old_dl03t_main` a view: `api.origin` que retornava uma série de atributos ao juntar: `origin`, `city`, `donatedpack` e `donor`, do schema `ingest` e precisa ser replicado para manter a visualização. Provavelmente será usada então `dl03t_main.ingest.vw01_origin`.
    - *Filtros:* Adicionado `api.vw_states_origin` ao bd `dl03t_main` que será utilizado para filtrar origens por estado.
    - *Filtros:* Adicionado `api.vw_donors_origin` ao bd `dl03t_main` que será utilizado para filtrar origens por donor.
    - *Consulta:* Para `ingest.vw01_origin` no bd `dl03t_main` resta atributo `city_id`.
- **Eclusa:** Resta atributos `cityname` e `err_msg`.

**Comment by ppKrauss** [comment]
* Donor: contempla propriedades do antigo `donor2`, contempla filtros  e retorna tudo na ausencia de parametros. Ver [Novidades](https://github.com/AddressForAll/WS/wiki/Novidades).

* Jurisdiction (antiga city). 
    - _cityname_ nao existe mais, agora eh `jurisdiction.name`, testar Novidades. O campo `err_msg` fica pendente ate padronizacao.
    - Estados sao segundo nivel administrativo debaixo de *country*, filtrar com http://api-test.addressforall.org/v1/vw_core/jurisdiction/parent_abbrev.lk.BR
    
... Demais consultas pendentes, desenhar qual melhor filtro

**Comment by venezianluis** [comment]
Objetos criados em dl03t_main: `api.vw_jurisd_origin`, `api.vw_donors_origin` são utilizados para montar os selects da api-origin.

**Comment by ppKrauss** [comment]
URLs para teste da versao [43cda4d](https://github.com/AddressForAll/site/commit/43cda4d106dc51f9d85ba73d9ba47627d395ee4d):
* http://addressforall.org/api-donor
* http://addressforall.org/api-origin
* http://addressforall.org/api-eclusa

Views a decidir como ficarao na versao definitiva:
* http://api-test.addressforall.org/_sql/vw_donors_origin
* http://api-test.addressforall.org/_sql/vw_jurisd_origin

**Comment by venezianluis** [comment]
f061d7090384c75174ba740cdff904cf087f8551 com implementação de `/v1.htm/` para trabalhar com DataTables

**Comment by ppKrauss** [comment]
ops, este ultimo commit gerou bugs:

* bug de implementacao em exemplos como http://api-test.addressforall.org/v1.htm/eclusa/checkuserfiles_step2/igor
* bug de especificacao: conforme solicitacoa e exemplo na versao anterior, nao se deve explodir o campo JSON, apenas trocar o valor por um botao ou icone onde o on-mouse-over ou o click (escolher o melhor) disparem ou um alert ou modal dialog com os dados (sem maior formatacao exceto "key: value" conforme sugerido em javascript de exemplo)

**Comment by ppKrauss** [comment]
* Bug, falta o NGINX e o PHP carregarem os parametros de URL para o filtro SQL PostgREST (projecao e selecao).
* Pendente: renomear para vw_core os antigos PHPs de api-donor,  api-origin e api-eclusa.

**Comment by ppKrauss** [comment]
Finalizacao: as navegacoes `/v1.htm` que nao reproduzem  exatamente o JSON deveriam ter nome diferenciado. Por exemplo ao inves de `vw_core/x` para a navegacao diferenciada seria `nav_core/x`, tendo a partir de entao, tal como `vw_`, o prefixo `nav_` como palavra reservada.

**Comment by ppKrauss** [comment]
APIs de navegacao `nav_`  implementadas, falta corridir **bug do step0** de http://api-test.addressforall.org/v1.htm/nav_eclusa

Em seguida revisaremos:

- [ ] teste. Uso do Back do navegador, funciona sempre? volta no estado esperado? (se instavel retomar uso do JSON by server-side).
- [ ] Paginacao, usar mesmo seletor de "todos" ou "n-items por pagina".
- [ ] Avaliar se interface das paginas `nav_` pode ser melhorada (estilo react)
- [ ] Avaliar se existe algum caso onde melhor trocar a API default pela grosseira, para multiplas colunas, ou algum recurso para visualizar/esconder verticalmente as colunas com valor JSON.

**Comment by ppKrauss** [comment]
Oops, paginas ainda com pequenos bugs:

* paginas `nav_*.php` precisam ser atualizadas com `api_default.inc.php` sempre, talvez mais simples usar includes comuns ou template comum entre elas para nao complicar futuras atualizacoes.

* http://api-test.addressforall.org/v1.htm/vw_core/donor  precisa entrar com dados, nao precisaria do botao (precisa?).

* Nova `api.inc.php` foi trazida da antiga  [WS/wiki/Novidades](http://git.AddressForAll.org/WS/wiki/Novidades)... Falta automatizar, bem como arrumar marcador de ancora (tal como modelo Github Readmes e Wikis).  <br/>Numa futura versao, depois de automatizar a listagem de APIs e seus exemplos, vale resgatar  o selecionador de pais/estado/cidade, como  na [antiga `default/api.inc.php`](https://github.com/AddressForAll/site/blob/2bb226fde91ee7d121142f6f184008f70250f429/default/api.inc.php) que devera mostra mais amigavelmente tudo o que temos porem seguindo a filtragem por nivel administrativo.

* Similarmente o novo endpoint HTML `nav_core/jurisdiction`  deve iniciar por mais global (paises ou Brasil) e oferecer navegacao para o zoom no detalhe desejado, de donor ou jurisdiction.

**Comment by ppKrauss** [comment]
@venezianluis vamos precisar revisar elementos da interface, http://api-test.addressforall.org/v1.htm/nav_eclusa
pois nao constam todas as colunas e informacoes. Sobretudo pack_id muito importante

**Comment by venezianluis** [comment]
atributos adicionados: `ctype`, `packid`

**Comment by venezianluis** [comment]
#### Consolidando em issue #20, qualquer pendência extra adicionamos lá também.
