### ISSUE TITLE
Cadastro e envio de e-mail

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/site#19]
O servidor foi configurado para o envio de e-mail.
Precisava testar a solução no site php 
para o envio de email para fora

**Comment by ppKrauss** [comment]
@venezianluis  arrumar index.php e cia para que formulario de **cadastro de email** e disparo de email (ex. via crontab) comecem a funcinar. Ideal que o PostgreSQL dispare, mas pode ser via PHP.  No ato do cadastro precisa ser enviado email pedindo confirmacao. 

Acertar testes e primeiros exemplos com @crebollobr

**Comment by venezianluis** [comment]
@crebollobr 
Necessitamos das especificações abaixo de smtp para poder desenvolver o script de disparo:
- User
- Password
- Port

**Comment by venezianluis** [comment]
Foram criados dois novos objetos na base `dt03t_main`:

- `optim.st_newsletter`: Tabela que armazena registros dos e-mails que solicitaram assinatura de newsletter.
- `api.add_st_newsletter`: Function que insere na tabela acima.

É possível fazer a chamada do rpc via POST em ambiente local:
`$.post('http://localhost:3103/rpc/add_st_newsletter', { email: "email@email" } );` -> Êxito.
Alguma ideia para como disparar esse post em Produção? Os objetos também foram criados em ambiente de produção.

**Comment by crebollobr** [comment]
Está configurado no localhost:25
ou no comando mail
sem autenticação

Em seg., 26 de out. de 2020 às 20:38, Luis Venezian <
notifications@github.com> escreveu:

**Comment by IgorEliezer** [comment]
Já que eu estou marcado como "assignee", eu tenho que fazer algo a respeito desta issue?

**Comment by crebollobr** [comment]
Boa noite,

Durante a semana podemos ver isso juntos, a noite.

Abraço,
Carlos Rebollo

Em sáb., 31 de out. de 2020 às 23:44, Igor Eliezer <notifications@github.com>
escreveu:

**Comment by ppKrauss** [comment]
Por favor registrarem o andamento desta task aqui nos comentarios.

**Comment by venezianluis** [comment]
Uma vez instanciado um objeto da classe [`PHPMailer`](https://github.com/PHPMailer/PHPMailer) é necessário atribuir as seguintes configurações para efetuar algum disparo, eu preciso identificar como preencher esses, você pode ajudar por gentileza? @crebollobr 
```PHP
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
    $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = 'localhost';                            // Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'user@example.com';                     // SMTP username
    $mail->Password   = 'secret';                               // SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
    $mail->Port       = 25;                                     // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above

    //Recipients
    $mail->setFrom('from@example.com', 'Mailer');

```

**Comment by venezianluis** [comment]
1. Configurado em `/addresforall.org/default/email_enviar.inc.php` a [url de disparo](http://addressforall.org/email_enviar) está retornando um erro ao conectar-se com smtp: `SMTP Error: Could not connect to SMTP host.`
2. Quando retirada a opção `$mail->isSMTP();` o erro também desaparece e é retornado uma mensagem de êxito, entretanto, o e-mail não é entregue, estou procurando algo na [documentação](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

Alguma ideia?

**Comment by crebollobr** [comment]
Olá,
O Servidor da microsoft não aceita "from" fora do nosso domínio, mas aceita "replay to". 
Essa ultima versão da biblioteca precisa colocar explicitamente que não quer autenticação e nem criptografia ( comunicação localhost )

**Comment by crebollobr** [comment]
Deu certo o teste, vou fechar
